// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: solana.proto

package solanaapp

import (
	"context"

	"github.com/yunsonggo/kline/app/solana_app/proto/solanapb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PingReq  = solanapb.PingReq
	PingResp = solanapb.PingResp

	SolanaApp interface {
		Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
	}

	defaultSolanaApp struct {
		cli zrpc.Client
	}
)

func NewSolanaApp(cli zrpc.Client) SolanaApp {
	return &defaultSolanaApp{
		cli: cli,
	}
}

func (m *defaultSolanaApp) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	client := solanapb.NewSolanaAppClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
