// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: solana.proto

package solanapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SolanaApp_Ping_FullMethodName = "/solanapb.SolanaApp/Ping"
)

// SolanaAppClient is the client API for SolanaApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolanaAppClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
}

type solanaAppClient struct {
	cc grpc.ClientConnInterface
}

func NewSolanaAppClient(cc grpc.ClientConnInterface) SolanaAppClient {
	return &solanaAppClient{cc}
}

func (c *solanaAppClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResp)
	err := c.cc.Invoke(ctx, SolanaApp_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolanaAppServer is the server API for SolanaApp service.
// All implementations must embed UnimplementedSolanaAppServer
// for forward compatibility.
type SolanaAppServer interface {
	Ping(context.Context, *PingReq) (*PingResp, error)
	mustEmbedUnimplementedSolanaAppServer()
}

// UnimplementedSolanaAppServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSolanaAppServer struct{}

func (UnimplementedSolanaAppServer) Ping(context.Context, *PingReq) (*PingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSolanaAppServer) mustEmbedUnimplementedSolanaAppServer() {}
func (UnimplementedSolanaAppServer) testEmbeddedByValue()                   {}

// UnsafeSolanaAppServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolanaAppServer will
// result in compilation errors.
type UnsafeSolanaAppServer interface {
	mustEmbedUnimplementedSolanaAppServer()
}

func RegisterSolanaAppServer(s grpc.ServiceRegistrar, srv SolanaAppServer) {
	// If the following call pancis, it indicates UnimplementedSolanaAppServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SolanaApp_ServiceDesc, srv)
}

func _SolanaApp_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolanaAppServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolanaApp_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolanaAppServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SolanaApp_ServiceDesc is the grpc.ServiceDesc for SolanaApp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SolanaApp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "solanapb.SolanaApp",
	HandlerType: (*SolanaAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SolanaApp_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "solana.proto",
}
