apiVersion: apps/v1
kind: Deployment
metadata:
  name: solana_app
  namespace: kline
  labels:
    app: solana_app
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: solana_app
  template:
    metadata:
      labels:
        app: solana_app
    spec:
      containers:
      - name: solana_app
        image: solana_app:v1
        ports:
        - containerPort: 10001
        readinessProbe:
          tcpSocket:
            port: 10001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 10001
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: solana_app-svc
  namespace: kline
spec:
  ports:
  - port: 10001
    targetPort: 10001
  selector:
    app: solana_app

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: solana_app-hpa-c
  namespace: kline
  labels:
    app: solana_app-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: solana_app
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: solana_app-hpa-m
  namespace: kline
  labels:
    app: solana_app-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: solana_app
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
