// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: solana.proto

package server

import (
	"context"

	"github.com/yunsonggo/kline/app/solana_app/internal/logic"
	"github.com/yunsonggo/kline/app/solana_app/internal/svc"
	"github.com/yunsonggo/kline/app/solana_app/proto/solanapb"
)

type SolanaAppServer struct {
	svcCtx *svc.ServiceContext
	solanapb.UnimplementedSolanaAppServer
}

func NewSolanaAppServer(svcCtx *svc.ServiceContext) *SolanaAppServer {
	return &SolanaAppServer{
		svcCtx: svcCtx,
	}
}

func (s *SolanaAppServer) Ping(ctx context.Context, in *solanapb.PingReq) (*solanapb.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
