// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type PingReq struct {
	Name string `json:"name"`
}

type PingResp struct {
	Status Status `json:"status"`
	Data   string `json:"data"`
}

type Status struct {
	Code  int32  `json:"code"`
	Msg   string `json:"msg"`
	Error string `json:"error"`
}
